---
name: qa-audit
preamble-tier: 3
version: 1.0.0
description: |
  QA methodology auditor. Scans a project's existing test suite and scores it against
  best practices across 5 dimensions: test pyramid balance, test isolation,
  test data strategy, assertion & naming quality, and CI/coverage & reliability.
  Produces a scored audit report (0–100) with concrete, ranked recommendations and
  before/after code examples. Checks include: test naming, AAA structure, shared state,
  sleep/timing, test data, coverage, CI integration, assertion quality (weak vs exact),
  positive/negative test balance, retry/skip/ignore markers, and parallelization safety.

  Consumes qa-methodology/references/ guides generated by /qa-methodology-refine for
  enriched, sourced recommendations. Falls back to built-in methodology knowledge when
  guides are not yet generated.

  Works standalone or as a sub-agent of /qa-team (writes report to $TEMP/qa-audit-report.md).

  Use when asked to:
  - "audit tests", "qa audit", "test quality review", "test methodology review"
  - "check test suite health", "is our testing good?", "improve our tests"
  - "test pyramid analysis", "why are our tests slow / flaky / brittle?"
  - "test coverage gaps", "how should we structure our tests?"
  (qa-agentic-team)
allowed-tools:
  - Bash
  - Read
  - Write
  - Glob
  - Grep
  - AskUserQuestion
disable-model-invocation: true
model: sonnet
effort: high
hooks:
  PreToolUse:
    - matcher: "Bash"
      hooks:
        - type: command
          command: 'bash "${CLAUDE_SKILL_DIR}/../bin/hooks/qa-pre-bash-safety.sh"'
  PostToolUse:
    - matcher: "Write|Edit"
      hooks:
        - type: command
          command: 'bash "${CLAUDE_SKILL_DIR}/../bin/hooks/qa-post-write-typecheck.sh"'
          async: true
---

## Version check

!`bash "${CLAUDE_SKILL_DIR}/../bin/qa-version-check-inline.sh" 2>/dev/null || echo "VERSION_STATUS: UPDATE_CHECK_FAILED"`

If `VERSION_STATUS` contains `UPGRADE_AVAILABLE` and `SKIP_UPDATE_ASK` is `0`, use `AskUserQuestion`: "qa-agentic-team update available. Update before running?" Options: "Yes — update now (recommended)" | "No — run with current version". If yes: `git -C "$_QA_ROOT" pull && bash "$_QA_ROOT/bin/setup"`. Continue regardless.

---

## Preamble (run first)

```bash
_TMP="${TEMP:-${TMP:-/tmp}}"
_DATE=$(date +%Y-%m-%d)
_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
echo "BRANCH: $_BRANCH"

# --- Test file discovery by layer ---
echo "--- TEST INVENTORY ---"
_UNIT=$(find . \( \
  -path "*/unit/*.spec.*" -o -path "*/unit/*.test.*" \
  -o -name "*.unit.spec.*" -o -name "*.unit.test.*" \
  -o -path "*/__tests__/unit*" \
  \) ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
_INTEG=$(find . \( \
  -path "*/integration/*.spec.*" -o -path "*/integration/*.test.*" \
  -o -name "*.integration.spec.*" -o -name "*.integration.test.*" \
  -o -path "*/__tests__/integration*" \
  \) ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
_E2E=$(find . \( \
  -path "*/e2e/*.spec.*" -o -path "*/e2e/*.test.*" \
  -o -name "*.e2e.spec.*" -o -name "*.e2e.test.*" \
  -o -path "*/tests/e2e*" \
  \) ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
_ALL_TESTS=$(find . \( \
  -name "*.spec.ts" -o -name "*.spec.js" \
  -o -name "*.test.ts" -o -name "*.test.js" \
  -o -name "*_test.py" -o -name "test_*.py" \
  -o -name "*Test.java" -o -name "*_spec.rb" \
  -o -name "*Tests.cs" -o -name "*Test.cs" -o -name "*Spec.cs" \
  \) ! -path "*/node_modules/*" ! -path "*/obj/*" 2>/dev/null | wc -l | tr -d ' ')
echo "UNIT: $_UNIT  INTEGRATION: $_INTEG  E2E: $_E2E  TOTAL: $_ALL_TESTS"

# --- Framework detection ---
echo "--- FRAMEWORK ---"
grep -ql '"jest"\|"vitest"\|"@testing-library"' package.json 2>/dev/null && echo "FRAMEWORK: jest/vitest (JS/TS)"
ls pytest.ini conftest.py pyproject.toml 2>/dev/null | head -1 | grep -q '.' && echo "FRAMEWORK: pytest (Python)"
ls pom.xml build.gradle 2>/dev/null | head -1 | grep -q '.' && echo "FRAMEWORK: JUnit (Java)"
ls Gemfile 2>/dev/null | grep -q '.' && echo "FRAMEWORK: RSpec (Ruby)"
find . -name "*.csproj" ! -path "*/obj/*" 2>/dev/null | grep -q '.' && echo "FRAMEWORK: .NET (C#)" && \
  { find . -name "*.csproj" ! -path "*/obj/*" 2>/dev/null | xargs grep -il "xunit" 2>/dev/null | grep -q '.' && echo "CS_FW: xunit"; } || \
  { find . -name "*.csproj" ! -path "*/obj/*" 2>/dev/null | xargs grep -il "MSTest" 2>/dev/null | grep -q '.' && echo "CS_FW: mstest"; } || \
  echo "CS_FW: nunit"

# --- Target language ---
echo "--- LANGUAGE ---"
_TARGET_LANG="typescript"
find . -name "pom.xml" ! -path "*/node_modules/*" 2>/dev/null | grep -q '.' && _TARGET_LANG="java"
find . \( -name "requirements.txt" -o -name "pyproject.toml" \) \
  ! -path "*/node_modules/*" 2>/dev/null | grep -q '.' && _TARGET_LANG="python"
find . -name "*.csproj" ! -path "*/obj/*" 2>/dev/null | grep -q '.' && _TARGET_LANG="csharp"
[ -f "Gemfile" ] && _TARGET_LANG="ruby"
echo "TARGET_LANG: $_TARGET_LANG"

# --- Coverage configuration ---
echo "--- COVERAGE ---"
grep -ql '"coverage"\|"nyc"\|"c8"' package.json 2>/dev/null && echo "COVERAGE_TOOL: nyc/c8"
ls .nycrc .nycrc.json jest.config.ts jest.config.js vitest.config.ts vitest.config.js 2>/dev/null | head -3
grep -r "coverageThreshold" --include="*.json" --include="*.ts" --include="*.js" \
  ! -path "*/node_modules/*" 2>/dev/null | head -3
grep -ql "pytest-cov\|coverage\[" requirements.txt pyproject.toml 2>/dev/null && echo "COVERAGE_TOOL: pytest-cov"
grep -r "\-\-cov-fail-under" --include="*.ini" --include="*.cfg" --include="*.toml" \
  2>/dev/null | head -3

# --- Flakiness signals ---
echo "--- FLAKINESS SIGNALS ---"
_SLEEP_COUNT=$(grep -r "sleep\|setTimeout\|Thread\.sleep\|time\.sleep" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
_RETRY_COUNT=$(grep -r "retry\|retries\|flaky\|\.skip\b\|\.only\b\|xtest\b\|xit\b\|xdescribe\b\|@Ignore\b\|\[Ignore\]\|\[Skip\]\|pytest\.mark\.skip\|pytest\.mark\.xfail\|jest\.retryTimes\|retries:.*[1-9]" \
  --include="*.spec.*" --include="*.test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
echo "SLEEP_CALLS: $_SLEEP_COUNT  RETRY_MARKS: $_RETRY_COUNT"

# --- BDD signals ---
echo "--- BDD ---"
_FEATURES=$(find . -name "*.feature" ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')
echo "FEATURE_FILES: $_FEATURES"
ls cucumber.js cypress.json jest-cucumber.config.* 2>/dev/null | head -2

# --- CI config ---
echo "--- CI ---"
ls .github/workflows/*.yml .circleci/config.yml .gitlab-ci.yml azure-pipelines.yml \
  Jenkinsfile 2>/dev/null | head -5

# --- MULTI-REPO SUPPORT ---
# Set QA_EXTRA_PATHS (space-separated absolute paths) to scan tests in other repos
# e.g.: export QA_EXTRA_PATHS="/path/to/e2e-repo /path/to/api-tests-repo"
if [ -n "$QA_EXTRA_PATHS" ]; then
  echo "MULTI_REPO_PATHS: $QA_EXTRA_PATHS"
  for _qr in $QA_EXTRA_PATHS; do
    _extra=$(find "$_qr" \( \
      -name "*.spec.ts" -o -name "*.spec.js" -o -name "*.test.ts" -o -name "*.test.js" \
      -o -name "*_test.py" -o -name "test_*.py" -o -name "*Test.java" \
      -o -name "*Tests.cs" -o -name "*_spec.rb" \) \
      ! -path "*/node_modules/*" ! -path "*/obj/*" 2>/dev/null | wc -l | tr -d ' ')
    echo "EXTRA_REPO $(basename "$_qr"): $_extra test files — $_qr"
  done
fi

# --- Mutation tool detection ---
echo "--- MUTATION TOOLS ---"
_STRYKER_AVAILABLE=0
grep -q '"@stryker-mutator/' package.json 2>/dev/null && _STRYKER_AVAILABLE=1
echo "STRYKER_AVAILABLE: $_STRYKER_AVAILABLE"

_PITEST_AVAILABLE=0
[ -f pom.xml ] && grep -q "pitest" pom.xml 2>/dev/null && _PITEST_AVAILABLE=1
echo "PITEST_AVAILABLE: $_PITEST_AVAILABLE"

_MUTMUT_AVAILABLE=0
command -v mutmut >/dev/null 2>&1 && _MUTMUT_AVAILABLE=1
echo "MUTMUT_AVAILABLE: $_MUTMUT_AVAILABLE"

_MUTAHUNTER_AVAILABLE=0
command -v mutahunter >/dev/null 2>&1 && _MUTAHUNTER_AVAILABLE=1
echo "MUTAHUNTER_AVAILABLE: $_MUTAHUNTER_AVAILABLE"

_DIFF_FILES=$(git diff --name-only 2>/dev/null | grep -E "\.(ts|tsx|js|jsx|py|java)$" | grep -v "spec\|test\|node_modules" || true)
_DIFF_COUNT=$(echo "$_DIFF_FILES" | grep -c '.' 2>/dev/null || echo 0)
echo "MUTATION_DIFF_FILES: $_DIFF_COUNT"
echo "$_DIFF_FILES" | head -10

_TEST_CMD=""
grep -q '"jest"' package.json 2>/dev/null && _TEST_CMD="npx jest --no-coverage"
grep -q '"vitest"' package.json 2>/dev/null && _TEST_CMD="npx vitest run"
{ [ -f pytest.ini ] || grep -q "\[tool.pytest" pyproject.toml 2>/dev/null; } && _TEST_CMD="python3 -m pytest"
[ -f pom.xml ] && _TEST_CMD="mvn test -q"
echo "TEST_CMD: ${_TEST_CMD:-none}"

echo "--- DONE ---"
```

If `_ALL_TESTS` is 0: warn the user that no test files were found. Recommend starting
with `/qa-methodology-refine test-pyramid` to understand testing strategy. Skip Phases
2–4 and produce a "No tests found" report.

If `MULTI_REPO_PATHS` output appeared: when sampling test files in Phase 1 and running
checks in Phase 2, include files from those extra paths. Language detection (`TARGET_LANG`)
uses CWD (the main application repository).

## Phase 1 — Test Inventory

Sample test files across all layers. Read up to 3 files from each detected layer:

```bash
# Sample unit tests
find . \( -path "*/unit/*.spec.*" -o -name "*.unit.spec.*" -o -name "*.unit.test.*" \) \
  ! -path "*/node_modules/*" 2>/dev/null | head -3

# Sample integration tests
find . \( -path "*/integration/*.spec.*" -o -name "*.integration.spec.*" \) \
  ! -path "*/node_modules/*" 2>/dev/null | head -3

# Sample e2e tests
find . \( -path "*/e2e/*.spec.*" -o -name "*.e2e.spec.*" \) \
  ! -path "*/node_modules/*" 2>/dev/null | head -3

# Sample unclassified tests (top-level spec files)
find . -maxdepth 4 \( -name "*.spec.ts" -o -name "*.spec.js" -o -name "*.test.ts" \) \
  ! -path "*/node_modules/*" ! -path "*/e2e/*" ! -path "*/unit/*" ! -path "*/integration/*" \
  2>/dev/null | head -5
```

Read the sampled files. For each, note the observed pattern and classify:

**Layer classification heuristics** (when file path isn't conclusive):
- Imports a real HTTP client (`fetch`, `axios`, `requests`, `RestAssured`) without mocking → **integration**
- Imports `playwright`, `cypress`, `selenium`, `detox`, `appium` → **e2e**
- Mocks all I/O dependencies → **unit**
- Mix of real and mocked dependencies → **integration**

Build the inventory table:

```
Layer        | Count | % of total | Sample files
-------------|-------|------------|-------------
Unit         |   N   |   N%       | path/to/file.spec.ts
Integration  |   N   |   N%       | path/to/file.spec.ts
E2E          |   N   |   N%       | path/to/file.spec.ts
Unclassified |   N   |   N%       | path/to/file.spec.ts
```

Ideal pyramid: **unit > 60%**, **integration 20–35%**, **e2e < 20%**.

## Phase 2 — Methodology Checks

Run these static checks and record concrete findings with file locations.

**Check 1: Test naming quality**

```bash
# Find vague test names
grep -rn "it\(\|test\(\|def test_\|@Test" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | \
  grep -iE "'test[0-9]*'|\"test[0-9]*\"|'it works'|'should work'|'does something'|'test this'" | head -10
```

Good: `"returns 401 when token is expired"` — describes behavior + expected outcome.
Bad: `"test auth"`, `"it works"`, `"test1"`.

**Check 2: Arrange-Act-Assert / Given-When-Then structure**

```bash
grep -rn "// Arrange\|// Act\|// Assert\|// Given\|// When\|// Then\|#arrange\|#act\|#assert" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | wc -l
```

Low count doesn't mean bad tests — read 3 unstructured test files to see if the
structure is implied but unwritten.

**Check 3: Test isolation — shared mutable state**

```bash
# let/var at describe scope (not reset in beforeEach) — JS/TS
grep -rn "^\s*let \|^\s*var " \
  --include="*.spec.ts" --include="*.spec.js" --include="*.test.ts" \
  ! -path "*/node_modules/*" 2>/dev/null | head -10

# beforeEach cleanup presence
grep -rn "beforeEach\|afterEach\|setUp\|tearDown\|setup_method\|teardown_method" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | wc -l
```

**Check 4: Sleep / timing dependencies (flakiness risk)**

```bash
grep -rn "sleep\|setTimeout.*[0-9]\{3,\}\|Thread\.sleep\|time\.sleep\|asyncio\.sleep" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | head -10
```

Each hardcoded sleep in a test is a flakiness risk. Report count + locations.

**Check 5: Test data strategy**

```bash
# Hardcoded literals in test bodies
_HARDCODED=$(grep -r "@example\.com\|password123\|test-user-[0-9]\|admin@\|\"admin\"" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')

# Factory / fixture usage
_FACTORY=$(grep -r "factory\|faker\|fixture\|\.build(\|\.create(\|Factory\.\|Faker\." \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | wc -l | tr -d ' ')

echo "HARDCODED: $_HARDCODED  FACTORY: $_FACTORY"
```

**Check 6: Coverage configuration**

Read the coverage config file (jest.config.ts, vitest.config.ts, pytest.ini, etc.).
Check:
- Coverage enabled: yes/no
- Thresholds configured: yes/no (if yes, what values?)
- Branch coverage measured: yes/no

**Check 7: CI test integration**

```bash
# Artifact-on-failure signals (screenshots, videos, test reports)
grep -r "upload-artifact\|store_artifacts\|publishTestResults\|junit\|screenshot\|video\|allure\|test-results" \
  --include="*.yml" --include="*.yaml" 2>/dev/null | head -5
```

Read the first CI config file found. Check:
- Tests run on every PR/push: yes/no
- Tests gate merge (required status check): inferred
- Separate stages (fast unit first, slow e2e last): yes/no
- Artifacts on failure (screenshots, videos, test reports uploaded): yes/no — relevant for integration/e2e debugging; less critical for unit tests

**Check 8: Assertion quality**

```bash
# Weak assertions — presence-only, not verifying exact values or behaviour
grep -rn "\.not\.toBeNull\(\)\|\.not\.toBeUndefined\(\)\|\.toBeDefined\(\)\|notBeNull\|assertNotNull\|IsNotNull\|Assert\.NotNull\|should\.exist\b\|is_not None\b\|ShouldNotBeNull\|should_not be_nil\|assertIsNotNone" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | head -15
```

Good: `expect(user.email).toBe('test@example.com')` — verifies the exact value.
Bad: `expect(user).not.toBeNull()`, `assertNotNull(result)` — only confirms the object exists; does not verify its content or behaviour.

Report count + locations. One or two null-guard assertions may be acceptable as a precondition; a pattern of *only* null-checks suggests tests that pass without actually exercising expected behaviour.

**Check 9: Positive/negative test balance**

```bash
# Test names describing negative / error paths
_NEG_TESTS=$(grep -rn "it(\|test(\|def test_\|@Test\b" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | \
  grep -iE "error|invalid|fail|reject|forbidden|unauthori[sz]ed|denied|missing|wrong|bad|should.not|cannot|throws?" | wc -l | tr -d ' ')

# Test names describing positive / happy paths
_POS_TESTS=$(grep -rn "it(\|test(\|def test_\|@Test\b" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | \
  grep -iE "success|returns?|creates?|gets?|fetches?|updates?|deletes?|should.*return|should.*create|should.*allow|200|201|204" | wc -l | tr -d ' ')
echo "POSITIVE_TEST_NAMES: $_POS_TESTS  NEGATIVE_TEST_NAMES: $_NEG_TESTS"
```

Healthy suite: both counts are non-zero and roughly balanced relative to suite size.
Red flag: `_NEG_TESTS = 0` — suite tests only the happy path; all error-case coverage is missing.
Red flag: `_NEG_TESTS >> _POS_TESTS` — may indicate over-focus on error handling while neglecting core behaviour tests.

**Check 10: Retry / ignore / skip markers**

```bash
grep -rn "\.skip\b\|\.only\b\|xtest\b\|xit\b\|xdescribe\b\|@Ignore\b\|\[Ignore\]\|\[Skip\]\|pytest\.mark\.skip\|pytest\.mark\.xfail\|pending()\|jest\.retryTimes\|retries:\s*[1-9]\|flaky" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | head -20
```

- **`.skip` / `@Ignore` / `[Ignore]`** — silently excludes tests; acceptable with a comment explaining why, problematic when used to suppress a failing test without a tracking issue
- **`.only`** — scopes the run to a single test; almost always a committed mistake
- **`retryTimes` / `retries:`** — masks flaky tests by hiding the root cause; prefer fixing the underlying race condition or timing issue instead
- **`pytest.mark.xfail`** — acceptable when the failure is documented and expected; flag if used without a `reason=` string

Report each occurrence with file and line. Any `.only` in committed code is a definite bug.

**Check 11: Parallelization safety**

```bash
# Hardcoded shared resources that cause worker conflicts under parallel execution
grep -rn "localhost:[0-9]\{4,\}\|\"port\".*[0-9]\{4,\}\|database.*['\"]test['\"]" \
  --include="*.spec.*" --include="*.test.*" --include="*_test.*" \
  ! -path "*/node_modules/*" 2>/dev/null | head -10

# Sequential / no-parallel flags in config — sign that tests force serial execution
grep -r "\-\-runInBand\|runInBand\|maxWorkers.*[\"']1[\"']\|workers.*=.*1\b\|singleThread\|sequentialTests" \
  --include="*.json" --include="*.ts" --include="*.js" --include="*.yml" --include="*.yaml" \
  ! -path "*/node_modules/*" 2>/dev/null | head -5
```

**Distinction from Check 7**: Check 7 looks at whether CI *runs* tests in parallel (good for speed). Check 11 looks at whether *test code* is safe to run in parallel.

Red flags: hardcoded ports or database names shared across test workers; `--runInBand` / `maxWorkers=1` suppressing parallelism to paper over race conditions instead of fixing them.
Green: tests use randomised/ephemeral ports, per-worker databases, or have no shared I/O resources.

## Phase 2.5 — Flaky Test Classification

Check `./qa-flaky-registry.json` if present for historical flake rates.

Identify candidates: test files flagged in Checks 4 and 10 (sleep/retry patterns, skipped tests).

For each candidate file (up to 5), run an isolation test:

```bash
# JS/TS (Jest/Vitest)
_ISOLATION_FILE="<file>"
if grep -q '"jest"\|"vitest"' package.json 2>/dev/null; then
  _RUNNER=$(grep -q '"vitest"' package.json && echo "vitest" || echo "jest")
  npx "$_RUNNER" --testPathPattern="$(basename "$_ISOLATION_FILE")" --no-coverage 2>&1 | tail -20
fi

# Python (pytest)
[ -f pytest.ini ] || [ -f pyproject.toml ] && \
  python3 -m pytest "$_ISOLATION_FILE" -q 2>&1 | tail -10
```

**Classify each flagged test**:
- Passes in isolation, fails in full suite → **Order-Dependent (OD)**
  Fix direction: add `beforeEach`/`afterEach` to reset shared state; avoid module-level mutations
- Fails in isolation too → **Implementation-Dependent (ID)**
  Fix direction: replace `setTimeout`/`sleep` with explicit waits; mock non-deterministic calls
- Only flagged by static signals, not confirmed by run → **Suspected-Flaky**

**Skip isolation run** if `qa-flaky-registry.json` shows `flakeRate > 0.3` for the test — use
registry classification directly.

Add classification column to the report's flakiness section:
```
| Test file | Type (OD/ID/Suspected) | Fix direction |
```

## Phase 3 — Load Methodology Guides

Check for pre-generated methodology guides:

```bash
ls qa-methodology/references/ 2>/dev/null || echo "No methodology guides found"
```

For each relevant guide present, read its "Anti-Patterns" and "Real-World Gotchas"
sections. Use these to enrich recommendations with specific, sourced callouts.

Relevant guide mapping:
- Pyramid issues → `qa-methodology/references/test-pyramid-guide.md`
- Sleep/timing issues → `qa-methodology/references/flakiness-guide.md`
- Hardcoded data → `qa-methodology/references/test-data-guide.md`
- Isolation issues → `qa-methodology/references/test-isolation-guide.md`
- Coverage issues → `qa-methodology/references/coverage-guide.md`
- CI issues → `qa-methodology/references/ci-cd-testing-guide.md`

If no guides exist, use built-in methodology knowledge and note:
"Run `/qa-methodology-refine <topic>` to generate richer guidance for this finding."

## Phase 2.7 — Risk-Weighted Coverage Gap Scoring (BL-013)

Skip if `QA_SKIP_RISK_SCORE=1` is set.

**Step 1 — Collect change and fix history**

```bash
_RECENT_CHANGED=$(git log --since="30 days ago" --name-only --format='' 2>/dev/null \
  | grep -E "\.(ts|tsx|js|jsx|py|java|cs|rb)$" | sort -u)
echo "RECENT_CHANGED_FILES: $(echo "$_RECENT_CHANGED" | grep -c '.' 2>/dev/null || echo 0)"

_FIX_FILES=$(git log --since="90 days ago" --format='' \
  --grep="fix\|bug\|patch\|hotfix\|defect" --name-only 2>/dev/null \
  | grep -E "\.(ts|tsx|js|jsx|py|java|cs|rb)$" | sort -u)
echo "FIX_COMMIT_FILES: $(echo "$_FIX_FILES" | grep -c '.' 2>/dev/null || echo 0)"

echo "RECENT_SAMPLE:"; echo "$_RECENT_CHANGED" | head -10
echo "FIX_SAMPLE:"; echo "$_FIX_FILES" | head -10
```

**Step 2 — Score each gap file**

| Signal | Points |
|--------|--------|
| File in `_RECENT_CHANGED` (changed last 30 days) | +3 |
| File in `_FIX_FILES` (fix/bug commit last 90 days) | +2 |
| Path contains `auth`, `payment`, `checkout`, `billing`, `password`, `token`, `session`, `wallet`, `stripe`, `oauth` | +3 |
| High complexity (>150 lines, nested conditionals, multiple exports) | +2 |
| Already has >50% statement coverage | −5 |

**Step 3 — Produce ranked Top 5 table**

```
## Risk-Weighted Coverage Gaps
| Rank | File | Risk Score | Signals |
|------|------|------------|---------|
| 1 | src/auth/login.ts | 8 | recently_changed + fix_commits + auth_path |
...
```

**Pass this ranked list to Phase 3.5** as the prioritized fill order — address files by risk score descending, not alphabetically or by coverage percentage alone.

---

## Phase 3.5 — Coverage Gap Fill Loop

Skip this phase if: no test runner is available, `_LANG` is not JS/TS or Python, or
coverage already meets threshold (0 source files below 80%). Threshold configurable via
`QA_COV_THRESHOLD` env var (default: 80).

**Step 1 — Run Coverage**

```bash
_COV_THRESHOLD="${QA_COV_THRESHOLD:-80}"

if grep -q '"jest"\|"vitest"' package.json 2>/dev/null; then
  _RUNNER=$(grep -q '"vitest"' package.json && echo "vitest" || echo "jest")
  npx "$_RUNNER" --coverage --coverageReporters=json --silent 2>/dev/null | tail -5
  _COV_FILE="coverage/coverage-summary.json"
elif [ -f pytest.ini ] || [ -f pyproject.toml ]; then
  python3 -m pytest --cov=. --cov-report=json -q 2>/dev/null | tail -5
  _COV_FILE="coverage.json"
else
  echo "COVERAGE: no supported runner found — skipping Phase 3.5"
  # Continue to Phase 4
fi
```

Parse coverage JSON and extract under-threshold files:

```python
python3 - << 'PYEOF'
import json, os, sys

threshold = int(os.environ.get('QA_COV_THRESHOLD', '80'))

# Try Jest coverage-summary.json
cov_file = 'coverage/coverage-summary.json'
if not os.path.exists(cov_file):
    cov_file = 'coverage.json'
if not os.path.exists(cov_file):
    print("COV_FILE: not found — skipping")
    sys.exit(0)

data = json.load(open(cov_file, encoding='utf-8'))

# Jest format: { "total": {...}, "path/to/file.ts": { "statements": {"pct": N}, ... } }
under = []
for path, metrics in data.items():
    if path == 'total':
        continue
    if isinstance(metrics, dict) and 'statements' in metrics:
        pct = metrics['statements'].get('pct', 100)
        if pct < threshold:
            under.append((path, pct))

under.sort(key=lambda x: x[1])
print(f"FILES_BELOW_{threshold}PCT: {len(under)}")
for f, pct in under[:10]:
    print(f"  {pct:.0f}% — {f}")
PYEOF
```

**Step 2 — Generate Targeted Tests** (up to 5 files per iteration, max 3 iterations)

For each under-threshold source file:
1. Read the source file
2. Identify uncovered functions/branches (lines with 0 hits in coverage data)
3. Read the project's existing test style (framework + naming conventions from similar spec files)
4. Generate targeted tests covering the uncovered paths
5. Append to existing spec file if present; create new spec file following project conventions
6. Write via Write tool

**Step 3 — Re-run Coverage** and compare before/after.

**Step 4 — Repeat** up to 3 total iterations until all files reach threshold or no further
progress is made.

Add coverage summary table to Phase 5 report:
```
| File | Coverage Before | Coverage After | Tests Generated |
```

## Phase 3.8 — Two-Tier Mutation Testing (BL-034)

Skip entirely if `QA_SKIP_MUTATION=1` or `_DIFF_COUNT=0`.

### Tier 1 — Tool-Based Incremental Mutation

**JS/TS** (if `_STRYKER_AVAILABLE=1`):
```bash
if [ "$_STRYKER_AVAILABLE" = "1" ] && [ "$_DIFF_COUNT" -gt 0 ]; then
  _MUTATE_GLOBS=$(echo "$_DIFF_FILES" | grep -E "\.(ts|tsx|js|jsx)$" | tr '\n' ',')
  [ -n "$_MUTATE_GLOBS" ] && \
    npx stryker run --mutate "${_MUTATE_GLOBS%,}" --incremental \
    --reporters json,clear-text 2>&1 | tail -40 | tee "$_TMP/qa-audit-stryker.txt"
fi
```

**Java** (if `_PITEST_AVAILABLE=1`):
```bash
if [ "$_PITEST_AVAILABLE" = "1" ] && [ "$_DIFF_COUNT" -gt 0 ]; then
  mvn pitest:mutationCoverage -DwithHistory=true -DmutationThreshold=60 -q 2>&1 \
    | tail -30 | tee "$_TMP/qa-audit-pitest.txt"
fi
```

**Python** (if `_MUTMUT_AVAILABLE=1`):
```bash
if [ "$_MUTMUT_AVAILABLE" = "1" ] && [ "$_DIFF_COUNT" -gt 0 ]; then
  _PY_DIFF=$(echo "$_DIFF_FILES" | grep "\.py$" | tr '\n' ' ')
  [ -n "$_PY_DIFF" ] && mutmut run --paths-to-mutate $_PY_DIFF 2>&1 \
    | tail -30 | tee "$_TMP/qa-audit-mutmut.txt"
  mutmut results 2>&1 | tail -20 | tee -a "$_TMP/qa-audit-mutmut.txt" 2>/dev/null || true
fi
```

Parse whichever output file was produced. Extract: raw mutation score %, total mutants, survived mutant list (file:line + mutation description).

### Tier 2 — Claude Survived Mutant Analysis

For each survived mutant (up to 20 per run), classify:
- **EQUIVALENT** — same observable behavior (e.g., `x <= 0` vs `x < 1` for integers, dead branches, cosmetic swaps). Exclude from adjusted score.
- **GENUINE-GAP** — real test gap. Generate a **killing assertion** in the project's test style.

Example:
```typescript
// Kills mutant at auth/login.ts:47 — `&&` changed to `||`
expect(canAccess({ role: 'user', verified: false })).toBe(false);
```

### Thresholds

- **Adjusted score** = killed / (total − EQUIVALENT_tool − EQUIVALENT_claude) × 100
- Score < 40%: **BLOCK** — CRITICAL finding; apply −5 to CI/Coverage dimension in Phase 4
- Score 40–59%: **WARN** — IMPORTANT finding
- Score ≥ 60%: PASS
- Override with `QA_SKIP_MUTATION_GATE=1`

Include in Phase 5 report:
```
## Mutation Testing (Phase 3.8)
- Tool: Stryker / Pitest / mutmut / none  Diff files: N
- Total mutants: N  Killed: N  Survived: N  Raw score: N%
- EQUIVALENT (tool): N  EQUIVALENT (Claude): N  Adjusted score: N% → PASS / WARN / BLOCK
- Killing assertions generated: N

| File:Line | Mutation | Classification | Killing Assertion |
|-----------|----------|----------------|-------------------|
```

---

## Phase 3.9 — MutaHunter LLM-Native Mutant Generation (BL-035)

**Opt-in only.** Skip unless ALL: `_MUTAHUNTER_AVAILABLE=1` AND `QA_MUTAHUNTER=1` AND `QA_SKIP_MUTATION!=1` AND `_DIFF_COUNT>0`.

**Few-shot seeding:**
```bash
if [ "${QA_MUTAHUNTER:-0}" = "1" ]; then
  git log --since="180 days ago" --format="%h %s" \
    --grep="fix\|bug\|patch\|hotfix" 2>/dev/null | head -5
fi
```
Read diffs of top 3 fix commits; note patterns (null-check additions, off-by-one fixes, auth guard insertions) as implicit mutation guidance.

**Run (up to 3 diff files, 50-mutant cap ~$0.05):**
```bash
if [ "$_MUTAHUNTER_AVAILABLE" = "1" ] && [ "${QA_MUTAHUNTER:-0}" = "1" ] && \
   [ "${QA_SKIP_MUTATION:-0}" != "1" ] && [ "$_DIFF_COUNT" -gt 0 ]; then
  for _mh_file in $(echo "$_DIFF_FILES" | head -3); do
    mutahunter run \
      --test-command "$_TEST_CMD" \
      --model "claude-haiku-4-5-20251001" \
      --source-path "$_mh_file" \
      --max-mutations 50 \
      2>&1 | tail -25 | tee -a "$_TMP/qa-audit-mutahunter.txt"
  done
fi
```

**Scientific debugging loop** (max 3 turns per survived mutant):
1. **Hypothesize**: why did this mutant survive (what code path isn't tested)?
2. **Generate**: minimal assertion targeting the gap.
3. **Validate**: explain why the assertion kills the mutant.
4. Refine once if hypothesis was incomplete.

Add sub-section to Phase 5 mutation block:
```
### MutaHunter Results (opt-in)
- Files: N  Mutants: N  Killed: N  Survived: N  Cost: ~$N
- Scientific debugging turns: N  Additional killing assertions: N
```

---

## Phase 4 — Score

Score 5 dimensions × 20 points each (100 total):

| Dimension | 0 | 10 | 20 | Signal |
|-----------|---|----|----|--------|
| Pyramid Balance | Inverted or all-e2e (> 50% e2e); no negative-path tests | Off-balance; some negative tests | Unit > 60%, e2e < 20%; positive + negative paths both covered | Inventory + Check 9 |
| Test Isolation | Shared state + no cleanup; parallel-unsafe resources | Some isolation | beforeEach resets + no cross-test deps + parallel-safe | Checks 3 & 11 |
| Test Data | All hardcoded values | Some factories | Factory/fixture ratio > hardcoded ratio | Check 5 |
| Assertion & Naming Quality | > 30% vague names or mostly presence-only assertions | Some descriptive names, some exact-value assertions | < 5% vague names; assertions verify exact values/structure | Checks 1 & 8 |
| CI / Coverage & Reliability | No CI; unexplained skips/retries everywhere | CI runs; some coverage | CI + thresholds + artifacts on failure + no unexplained skips | Checks 4, 6, 7 & 10 |

A score of 50–65 is typical for projects that haven't explicitly focused on test
methodology. Report the score with context, not judgment.

## Phase 5 — Audit Report

Write to `$_TMP/qa-audit-report.md` AND print to console.

```markdown
# QA Audit Report — <date> — <branch>

## Overall Score: <N>/100 — <Excellent ≥80 | Good 65–79 | Fair 50–64 | Needs Work <50>

### Dimension Scores
| Dimension | Score | Finding |
|-----------|-------|---------|
| Pyramid Balance | N/20 | N% unit / N% integration / N% e2e · positive/negative balance: yes/partial/no |
| Test Isolation | N/20 | N shared-state risks · parallelization safety: safe/unsafe/unknown |
| Test Data | N/20 | N hardcoded / N factory usages |
| Assertion & Naming Quality | N/20 | N vague names · N weak/presence-only assertions |
| CI / Coverage & Reliability | N/20 | Coverage: yes/no · Thresholds: yes/no · Artifacts on failure: yes/no · Skips/retries: N |

## Test Inventory
| Layer | Count | % |
|-------|-------|---|
| Unit | N | N% |
| Integration | N | N% |
| E2E | N | N% |
| Unclassified | N | N% |

**Pyramid verdict:** <On target | Over-indexed on E2E — raise unit ratio | Inverted pyramid — most tests are slow>

## Recommendations
Ranked by impact (CRITICAL → IMPORTANT → NICE-TO-HAVE):

### 1. [CRITICAL / IMPORTANT / NICE-TO-HAVE] <Short title>
**Problem:** <Concrete finding — file:line if possible>
**Impact:** <Why this matters — flakiness, false confidence, maintenance cost, slow CI>
**Fix:**
```<language>
// Before: (use the project's detected TARGET_LANG for all code examples)
<actual code or pattern found in the project>

// After:
<corrected code using best practice>
```
**Guide:** `qa-methodology/references/<topic>-guide.md`

... (up to 5 recommendations) ...

## Flakiness & Reliability Summary
- Hardcoded sleeps: N locations (risk: LOW / MEDIUM / HIGH)
- Skipped / ignored / retry-marked tests: N (list any `.only` markers — these are always bugs if committed)
- Weak assertions (presence-only, not value-checking): N locations
- Tests missing negative/error paths: yes / partial / no
- Overall flakiness risk: LOW / MEDIUM / HIGH

## BDD / Structured Testing
- Feature files: N
- BDD patterns: present / absent
- AAA/GWT markers: N occurrences

## Methodology Guides Available
<list qa-methodology/references/*.md with one-line descriptions>
OR
"No methodology guides generated yet. Run `/qa-methodology-refine <topic>` to enrich future audits."
```

## CTRF Output

```python
python3 - << 'PYEOF'
import json, os, time

tmp = os.environ.get('TEMP') or os.environ.get('TMP') or '/tmp'
report_path = os.path.join(tmp, 'qa-audit-report.md')

# Read score from report if available
score = 0
try:
    content = open(report_path, encoding='utf-8').read()
    import re
    m = re.search(r'Overall Score:\s*(\d+)/100', content)
    if m:
        score = int(m.group(1))
except:
    pass

# 5 methodology dimension tests — map to passed/failed based on score tiers
dimensions = [
    ('Pyramid Balance',            score >= 60),
    ('Test Isolation',             score >= 55),
    ('Test Data',                  score >= 50),
    ('Assertion & Naming Quality', score >= 55),
    ('CI / Coverage & Reliability', score >= 50),
]

tests = []
for name, passed in dimensions:
    tests.append({
        'name': name,
        'status': 'passed' if passed else 'failed',
        'duration': 0,
        'suite': 'methodology',
    })

# Add OD/ID flaky tests as individual entries
flaky_registry = 'qa-flaky-registry.json'
if os.path.exists(flaky_registry):
    try:
        reg = json.load(open(flaky_registry, encoding='utf-8'))
        for key, info in reg.get('tests', {}).items():
            if info.get('flakeRate', 0) > 0.2:
                tests.append({
                    'name': key,
                    'status': 'failed',
                    'duration': 0,
                    'suite': 'flakiness',
                    'message': f'flakeRate={info["flakeRate"]:.2f} ({info.get("classification","suspected")})',
                })
    except:
        pass

passed_count = sum(1 for t in tests if t['status'] == 'passed')
failed_count = sum(1 for t in tests if t['status'] == 'failed')
now_ms = int(time.time() * 1000)

ctrf = {
    'results': {
        'tool': {'name': 'qa-audit'},
        'summary': {
            'tests': len(tests),
            'passed': passed_count,
            'failed': failed_count,
            'pending': 0,
            'skipped': 0,
            'other': 0,
            'start': now_ms - 1000,
            'stop': now_ms,
        },
        'tests': tests,
        'environment': {'reportName': 'qa-audit', 'score': score},
    }
}

out = os.path.join(tmp, 'qa-audit-ctrf.json')
json.dump(ctrf, open(out, 'w', encoding='utf-8'), indent=2)
print(f'CTRF_WRITTEN: {out}')
print(f'  tests={len(tests)} passed={passed_count} failed={failed_count} score={score}')
PYEOF
```

## Important Rules

- **Read actual test files** — scan content, not just file counts; a directory named `unit/` may contain integration tests
- **Concrete examples** — every recommendation must show actual code from the project (before) and the fix (after)
- **Report even with 0 tests** — produce the report; recommend starting with `/qa-methodology-refine test-pyramid`
- **No judgment on score** — a low score means opportunity, not blame; frame positively
- **Link to guides** — when a methodology guide exists for a finding, reference it explicitly
- **Idempotent** — safe to re-run; always overwrites `$_TMP/qa-audit-report.md`

## Agent Memory

After each run, update the memory file at `.claude/agent-memory/qa-audit/MEMORY.md` (create if absent). Record:
- Detected framework, version, and config file paths
- Auth endpoint and credential format used
- Recurring failures or known flaky scenarios
- Base URL confirmed working
- Any test infrastructure quirks discovered

Read this file at the start of each run to skip re-detection of already-known facts.

## Telemetry (run last)

```bash
~/.claude/skills/gstack/bin/gstack-timeline-log \
  '{"skill":"qa-audit","event":"completed","branch":"'"$_BRANCH"'","date":"'"$_DATE"'"}' \
  2>/dev/null || true
```
